### ISSUE TITLE
No response after enter question

### ISSUE THREAD

**Issue by waynechungvs** [aquivalabs/my-org-butler#10]
**Describe the bug**
Follow along the steps but can't make butler answer.

**Version of MyOrgButler (see Setup > Installed Packages):**

1.19

**To Reproduce**
1. Go to App Launcher
2. Find  'VSE Sales Lightning'
3. Open My Org Butler from left bottom
4. Type in any question.

**Expected behavior**
Should have response return

**Screenshots**
![Org_Bulter_Error](https://github.com/aquivalabs/my-org-butler/assets/105181305/476a1d74-b6df-4d67-949a-9e2276d688e3)

**Additional context**
![image](https://github.com/aquivalabs/my-org-butler/assets/105181305/9f9e2861-c8dd-4b6c-813e-441f8ef3d510)
![image](https://github.com/aquivalabs/my-org-butler/assets/105181305/edc713fb-9072-4ad1-a22c-9148988aedcf)

![image](https://github.com/aquivalabs/my-org-butler/assets/105181305/be7dce5b-6efe-4750-acd2-15a90e5db741)

**Comment by rsoesemann** [comment]
Please change the following:

1. Remove the postman collection File. Its not needed. Where did you get that from. I actually deleted this requirement
2. Deactivate Code Interpreter and Retrieval
3. Make sure to use the latest instruction.txt and ALL Functions

**Comment by waynechungvs** [comment]
> You can also try to use my assistant id: asst_cN3f0Ir8Pb83Le7IersrLCWf. Does that work across OpenAi accounts?
If I try this, the error message is:
![image](https://github.com/aquivalabs/my-org-butler/assets/105181305/7ca95908-4e4b-4eab-be7e-43df7052711d)

**Comment by waynechungvs** [comment]
> @waynechungvs Please change the following and try again
> 
> 1. Remove the postman collection File. Its not needed. Where did you get that from. I actually deleted this requirement
> 2. Deactivate Code Interpreter and Retrieval
> 3. Make sure to use the latest instruction.txt and ALL Functions

Try all above three points, but still same without error message no response. FYI, I copy instruction.txt and ALL Functions from your main branch. Do you have any idea? 
![image](https://github.com/aquivalabs/my-org-butler/assets/105181305/9eddaa19-2840-4e40-a0e5-9e3d93327114)

**Comment by rsoesemann** [comment]
Any indicators of errors in the Dev Console Debug Log? I see this

![Screenshot 2024-04-04 at 12 27 11](https://github.com/aquivalabs/my-org-butler/assets/8180281/2210e956-dacb-4272-b4b4-f5392c2f2926)


![Screenshot 2024-04-04 at 12 27 28](https://github.com/aquivalabs/my-org-butler/assets/8180281/80b1724c-afe0-48c6-9e0a-410256036a9d)

**Comment by waynechungvs** [comment]
Hi @rsoesemann, I am not sure what suppose to see in dev cconsole so I jsut download the log and attached it , let me know what  I can provide for this. I really look forward to try this app.
I am thinking if that's easier if we can schedule a quick call to do screen demo so I can show you what's my config.  
![image](https://github.com/aquivalabs/my-org-butler/assets/105181305/3414d3dd-701c-4061-8004-502df300a79c)
[apex-07LTH000002LUBj2AO.log](https://github.com/aquivalabs/my-org-butler/files/14901648/apex-07LTH000002LUBj2AO.log)

**Comment by rsoesemann** [comment]
Sure can you send me a Europe compatible invite?

**Comment by waynechungvs** [comment]
> Sure can you send me a Europe compatible invite?

Hi @rsoesemann can you provide the email that I can find you so I can set up and send you a Microsoft Teams meeting invitation?  Thanks.

**Comment by rsoesemann** [comment]
I don't want to share my email here. Please lets connect in Linkedin where we first met

**Comment by waynechungvs** [comment]
It turns out is issue on the Open AI side is not related to this tool. After correcting the config on the OpenAI side, it works as expected.

**Comment by waynechungvs** [comment]
It turns out is issue on the Open AI side is not related to this tool. After correcting the config on the OpenAI side, it works as expected.

**Comment by rsoesemann** [comment]
Thanks @waynechungvs, for testing. Glad I could help you resolve the issue.
