### ISSUE TITLE
Question: challenges with heap size and callout size

### ISSUE THREAD

**Issue by multimanic** [aquivalabs/my-org-butler#13]
@rsoesemann wrote about this project in this [SF-Ben article](https://www.salesforceben.com/beyond-the-hype-our-experience-of-building-3-salesforce-ai-apps/).

What did he mean by "challenges arose with heap size and callout size"? I just tried calling the OpenAI chat API from Apex with 16k tokens and had no issues. Is there anything I should be aware of?

Thanks

**Comment by rsoesemann** [comment]
My comment was related to the other tool I described in the article: https://github.com/aquivalabs/document-mess-detector

The butler has no such issues.
