### ISSUE TITLE
question: why use named credentials to call OpenAI endpoints?

### ISSUE THREAD

**Issue by multimanic** [aquivalabs/my-org-butler#14]
I've noticed you are utilizing named credentials to store to call the OpenAI endpoints. It seems to me like you are doing this to store the OpenAI API key. So my question is if using a custom setting field wouldn't be much easier for the sys admin installing you package. Personally I struggled a lot with the Named Credentials, External Named Credentials, Principals, Parameter Name, etc.

Hence my question why you chose this route.

Thanks

**Comment by multimanic** [comment]
Any thoughts? Did you use named credentials instead of e.g. custom settings because there is a requirement for managed packages?

**Comment by rsoesemann** [comment]
Sorry to respond so late. Yes. Aquiva Labs is a PDO Partner and we know that if this would be a Managed Package a native artefact like Named Credentia is a better and preferred way to authenticate with APIs.
